export const Get_User = "Get_User"
export const Get_Name = "Get_Name"
export const Get_Email = "Get_Email"
export const Get_Phone = "Get_Phone"
export const Get_UserId = "Get_UserId"
export const Get_Show="Get_Show"
